format = """
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[ ](fg:#FCA17D)\
"""
right_format = """
[](fg:#06969A)\
$cmd_duration\
[](fg:#86BBD8 bg:#06969A)\
$cmake\
$golang\
$lua\
$python\
$rust\
[](fg:#33658A bg:#86BBD8)\
$hostname\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#FFFFFF bg:#9A348E"
style_root = "fg:#FFFFFF bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:#FFFFFF bg:#9A348E"
disabled = false # Disabled by default

[os.symbols]
Manjaro = "  "

[directory]
style = "fg:#FFFFFF bg:#DA627D"
read_only = " "
format = "[ ($read_only)]($style)[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo=false
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "
style = "fg:#1b1b1b bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#1b1b1b bg:#FCA17D"
untracked = "?$count"
modified = "!$count"
conflicted = "=$count"
format = '[$all_status$ahead_behind ]($style)'

# right format
[cmd_duration]
style = "fg:#FFFFFF bg:#06969A"
format = "[ $duration  ]($style)"

[cmake]
symbol = "󱁤"
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = "󰢱"
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[rust]
symbol = ""
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[hostname]
format = "[ $hostname ]($style)"
ssh_only = false
style = "fg:#FFFFFF bg:#33658A"

